
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-07
owner: ucsb-cs156-f24
repo_name: team01-f24-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"Ponmo-delete-help-request-endpoint","number":52,"title":"Add DELETE endpoint for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/52"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-add-delete-endpoint-articles","number":51,"title":"Add DELETE endpoint for a specific record in Articles table","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/51"},{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"GET-help-request","number":50,"title":"Add get request for HelpRequests by id","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/50"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"ramon-w-articles-get-by-id","number":49,"title":"Add GET (show) endpoint for a single record in Articles table","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/49"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-team-tasks","number":44,"title":"ld - added table to README.md and updated the dokku links","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/44"}]
