
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-07
owner: ucsb-cs156-f24
repo_name: team01-f24-07
pull_requests: [{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-organization-get","number":56,"title":"ld -  add \"get\" hook for Organization API","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/56"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-organizations-post-get","number":55,"title":"Create UCSBOrganizationController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/55"},{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"Ponmo-edit-help-request-endpoint","number":54,"title":"Create PUT endpoint for Help Requests","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/54"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-articles-put-endpoint","number":53,"title":"Add PUT (edit) endpoint for a single record in Articles table","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/53"},{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"GET-help-request","number":50,"title":"Add get request for HelpRequests by id","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/50"}]
