
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-07
owner: ucsb-cs156-f24
repo_name: team01-f24-07
pull_requests: [{"author":{"id":"U_kgDOBo-IIw","is_bot":false,"login":"eug-wong","name":"Eugene Wong"},"headRefName":"ew-delete-endpoint-menuItemReview","number":64,"title":"added delete endpoint for MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/64"},{"author":{"id":"U_kgDOBo-IIw","is_bot":false,"login":"eug-wong","name":"Eugene Wong"},"headRefName":"ew-put-endpoint-menuItemReview","number":63,"title":"Put endpoint menu item review","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/63"},{"author":{"id":"U_kgDOB3EPsA","is_bot":false,"login":"kanav9063","name":""},"headRefName":"ka-team01-#9","number":62,"title":"Create UCSBDiningCommonsMenuItemController, add GET (index) and POST (create) #9","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/62"},{"author":{"id":"U_kgDOB3EPsA","is_bot":false,"login":"kanav9063","name":""},"headRefName":"ka-team01-#8","number":61,"title":"Create database table for UCSBDiningCommonsMenuItem #8","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/61"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-organization-complete-controller","number":60,"title":"Ld organization complete controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/60"},{"author":{"id":"U_kgDOCL-Znw","is_bot":false,"login":"divyagsubramonian","name":"Divya Subramonian"},"headRefName":"Divya-ReqRequestTable","number":58,"title":"DS - Created the database table for RecommendationRequest","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/58"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-articles-put-endpoint","number":53,"title":"Add PUT (edit) endpoint for a single record in Articles table","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/53"}]
