
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-07
owner: ucsb-cs156-f24
repo_name: team01-f24-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"Ramon-W-articles-db-table","number":45,"title":"Add database table for Articles","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/45"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-team-tasks","number":44,"title":"ld - added table to README.md and updated the dokku links","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/44"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-ucsb-cs156-f24-create-db","number":43,"title":"ld - created UCSBOrganization database files","url":"https://github.com/ucsb-cs156-f24/team01-f24-07/pull/43"}]
